version: "2"
checks:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: rulesets.xml
  similar-code:
    config:
      threshold: 112
  identical-code:
    config:
      threshold: 86
    exclude_patterns:
      - "src/Phug/Phug/Phug/Optimizer.php"
exclude_patterns:
  - "**/tests/**"
