---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: rulesets.xml
plugins:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
