version: "2"
checks:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: rulesets.xml
  similar-code:
    config:
      threshold: 106
  identical-code:
    config:
      threshold: 80
  file-lines:
    enabled: true
    config:
      threshold: 400
  method-count:
    enabled: true
    config:
      threshold: 30
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 6
  method-complexity:
    enabled: true
    config:
      threshold: 7
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - "src/Phug/Phug/Phug/Optimizer.php"
exclude_patterns:
  - "**/tests/**"
