pug-php/pug:
  install:
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

pug/bemto:
  autoload:
    - cp -r vendor/phug/phug vendor/phug/compiler
    - cp -r vendor/phug/phug vendor/phug/formatter
    - composer self-update 1.10.17
    - composer dump-autoload --optimize --no-interaction --quiet
    - composer self-update --2

pug-php/pug-assets:
  install:
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

pug-php/pug-minify:
  install:
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

pug/slim:
  install:
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

pug/twig:
  autoload:
    - cp -r vendor/phug/phug vendor/phug/compiler
    - composer self-update 1.10.17
    - composer dump-autoload --optimize --no-interaction --quiet
    - composer self-update --2

ci-pug/ci-pug:
  install:
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

bkwld/laravel-pug:
  install:
    - composer config --no-plugins allow-plugins.pug/installer true
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction

pug/yii2:
  install:
    - composer config --no-plugins allow-plugins.yiisoft/yii2-composer true
    - composer config --no-plugins allow-plugins.nodejs-php-fallback/nodejs-php-fallback true
    - composer install --no-interaction
