pug-php/pug:
  source:
    success_only: true
    url: https://github.com/pug-php/pug.git
    reference: master
  install: github
  script: github

pug/bemto:
  autoload:
    - cp -r vendor/phug/phug vendor/phug/compiler
    - cp -r vendor/phug/phug vendor/phug/formatter
    - composer dump-autoload --optimize --no-interaction --quiet

pug-php/pug-assets:
  allow-plugins: nodejs-php-fallback/nodejs-php-fallback

pug-php/pug-minify:
  allow-plugins: nodejs-php-fallback/nodejs-php-fallback

#pug/slim:
#  allow-plugins: nodejs-php-fallback/nodejs-php-fallback

pug/twig: default

ci-pug/ci-pug:
  allow-plugins: nodejs-php-fallback/nodejs-php-fallback

bkwld/laravel-pug:
  source:
    success_only: true
    url: https://github.com/BKWLD/laravel-pug.git
    reference: master
  install: github
  script: github

pug/yii2:
  allow-plugins:
    - yiisoft/yii2-composer
    - nodejs-php-fallback/nodejs-php-fallback
