#!/usr/bin/php
<?php

use Phug\Cli;

include 'vendor/autoload.php';

$cli = new Cli('Phug', [
    'render',
    'renderFile',
    'compile',
    'compileFile',
    'display' => 'render',
    'displayFile' => 'renderFile',
    'cacheDirectory' => function ($facade, $arguments) {
        list($success, $errors, $errorDetails) = call_user_func_array([$facade, 'cacheDirectory'], $arguments);

        return
            "$success templates cached.\n".
            "$errors templates failed to be cached.\n".
            implode('', array_map(function ($detail) {
                return $detail['inputFile']."\n".
                    $detail['error']->getMessage()."\n".
                    $detail['error']->getTraceAsString();
            }, $errorDetails));
    },
]);

exit($cli->run($argv) ? 0 : 1);
