---
version: "2"
plugins:
    duplication:
        enabled: true
        config:
            languages:
            - ruby
            - javascript
            - python
            - php
    fixme:
        enabled: true
    phpcodesniffer:
        enabled: true
    phpmd:
        enabled: true
    SonarPHP:
        enabled: true
    phan:
        enabled: true
exclude_patterns:
- "tests/"
