name: Split

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v5
#      with:
#        path: vendor
#        key: split-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          split-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        test -f composer.json && mv composer.json composer.json.save -f
        composer require "phug/split:^1.5.1" --no-interaction
        test -f composer.json.save && mv composer.json.save composer.json -f

    - name: Split monorepository
      run: vendor/bin/split update --git-credentials=$SPLIT_REPOSITORY_CREDENTIALS
      env:
        SPLIT_REPOSITORY_CREDENTIALS: ${{ secrets.SPLIT_REPOSITORY_CREDENTIALS }}
